'use strict';
const $=id=>document.getElementById(id), canvas=$('track'),ctx=canvas.getContext('2d');
const tables={plane:{0:'MANUAL',1:'CIRCLE',2:'STABILIZE',3:'TRAINING',4:'ACRO',5:'FBWA',6:'FBWB',7:'CRUISE',8:'AUTOTUNE',10:'AUTO',11:'RTL',12:'LOITER',13:'TAKEOFF',14:'AVOID_ADSB',15:'GUIDED',17:'QSTABILIZE',18:'QHOVER',19:'QLOITER',20:'QLAND',21:'QRTL',22:'QAUTOTUNE',23:'QACRO',24:'THERMAL',25:'LOITER_ALT_QLAND',26:'AUTOLAND'},copter:{0:'STABILIZE',1:'ACRO',2:'ALT_HOLD',3:'AUTO',4:'GUIDED',5:'LOITER',6:'RTL',7:'CIRCLE',9:'LAND',11:'DRIFT',13:'SPORT',14:'FLIP',15:'AUTOTUNE',16:'POSHOLD',17:'BRAKE',18:'THROW',19:'AVOID_ADSB',20:'GUIDED_NOGPS',21:'SMART_RTL',22:'FLOWHOLD',23:'FOLLOW',24:'ZIGZAG',25:'SYSTEMID',26:'AUTOROTATE',27:'AUTO_RTL'},rover:{0:'MANUAL',1:'ACRO',3:'STEERING',4:'HOLD',5:'LOITER',6:'FOLLOW',7:'SIMPLE',10:'AUTO',11:'RTL',12:'SMART_RTL',15:'GUIDED'}};
const palette=['#52dfb4','#83a7ff','#ffbe6a','#f18bd0','#64cff0','#be9aff','#eb8585','#bada73'];
let log=null,selected=0,hover=-1,colors=new Map(),view={scale:1,cx:0,cy:0},W=1,H=1,drag=null,playing=false,lastFrame=0,playTime=0,loadToken=0,worker=null;
const fmt=(n,d=1)=>n===null||n===undefined||!Number.isFinite(Number(n))?'—':Number(n).toFixed(d);
const clock=t=>{t=Math.max(0,Math.floor(t));return `${Math.floor(t/60).toString().padStart(2,'0')}:${(t%60).toString().padStart(2,'0')}`;};
const modeName=m=>m===null?'未知模式':tables[$('vehicle').value]?.[m]||`MODE ${String(m)}`;
const color=m=>colors.get(String(m))||'#91a9bb';
function rows(p){return [['日志时间',`${fmt(p.t,3)} s`],['轨迹相对时间',clock(p.elapsed)],['地速',`${fmt(p.speed)} m/s`],['空速',`${fmt(p.airspeed)} m/s`],['GPS 海拔',`${fmt(p.alt)} m`],['相对起飞点高度',`${fmt(p.relativeAlt)} m`],['纬度',fmt(p.lat,7)],['经度',fmt(p.lon,7)],['横滚 / 俯仰',`${fmt(p.roll)}° / ${fmt(p.pitch)}°`],['卫星数 / HDOP',`${fmt(p.satellites,0)} / ${fmt(p.hdop,2)}`],['电池电压',`${fmt(p.voltage,2)} V`]];}
function details(i,isHover=false){if(!log)return;const p=log.points[i];$('modebadge').textContent=modeName(p.mode);$('modebadge').style.color=color(p.mode);$('pointstate').textContent=isHover?'悬停位置':`定位点 ${i+1}`;$('details').replaceChildren(...rows(p).map(([k,v])=>{const el=document.createElement('div');el.className='data-row';const a=document.createElement('span'),b=document.createElement('strong');a.textContent=k;b.textContent=v;el.append(a,b);return el;}));}
function legend(){ $('legend').replaceChildren(...[...colors].map(([m,c])=>{const el=document.createElement('span'),dot=document.createElement('i');dot.style.background=c;el.append(dot,document.createTextNode(modeName(m==='null'?null:m)));return el;}));}
function screen(p){return {x:W/2+(p.x-view.cx)*view.scale,y:H/2-(p.y-view.cy)*view.scale};}
function fit(){if(!log)return;const xs=log.points.map(p=>p.x),ys=log.points.map(p=>p.y);let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const x of xs){minX=Math.min(minX,x);maxX=Math.max(maxX,x);}for(const y of ys){minY=Math.min(minY,y);maxY=Math.max(maxY,y);}view={cx:(minX+maxX)/2,cy:(minY+maxY)/2,scale:Math.min((W-120)/Math.max(20,maxX-minX),(H-120)/Math.max(20,maxY-minY))};draw();}
function size(c){const r=c.getBoundingClientRect(),dpr=window.devicePixelRatio||1;c.width=Math.round(r.width*dpr);c.height=Math.round(r.height*dpr);const cctx=c.getContext('2d');cctx.setTransform(dpr,0,0,dpr,0,0);return {w:r.width,h:r.height};}
function resize(){const s=size(canvas);W=s.w;H=s.h;size($('profile'));if(log)fit();else draw();}
function draw(){ctx.fillStyle='#0e1823';ctx.fillRect(0,0,W,H);const ideal=90/view.scale,power=10**Math.floor(Math.log10(ideal)),step=([1,2,5,10].find(n=>n*power>=ideal)||10)*power;ctx.lineWidth=1;ctx.strokeStyle='#203043';ctx.fillStyle='#5f7d92';ctx.font='10px Segoe UI';const x0=view.cx-W/(2*view.scale),y0=view.cy-H/(2*view.scale);for(let x=Math.ceil(x0/step)*step;x<x0+W/view.scale;x+=step){const s=screen({x,y:0});ctx.beginPath();ctx.moveTo(s.x,0);ctx.lineTo(s.x,H);ctx.stroke();ctx.fillText(`${Math.round(x)} E`,s.x+5,H-39);}for(let y=Math.ceil(y0/step)*step;y<y0+H/view.scale;y+=step){const s=screen({x:0,y});ctx.beginPath();ctx.moveTo(0,s.y);ctx.lineTo(W,s.y);ctx.stroke();ctx.fillText(`${Math.round(y)} N`,8,s.y-5);}if(!log)return;
 const pts=log.points;ctx.lineWidth=2.6;ctx.lineJoin='round';ctx.lineCap='round';for(let i=1;i<pts.length;i++){if(pts[i].break)continue;const a=screen(pts[i-1]),b=screen(pts[i]);ctx.strokeStyle=color(pts[i-1].mode);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
 function marker(p,c,label){const s=screen(p);ctx.fillStyle=c;ctx.beginPath();ctx.arc(s.x,s.y,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e7f0f7';ctx.fillText(label,s.x+9,s.y-9);}marker(pts[0],'#52dfb4','起点');marker(pts.at(-1),'#ffbe6a','终点');
 const p=screen(pts[hover>=0?hover:selected]);ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.fillStyle=color(pts[hover>=0?hover:selected].mode);ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.fill();ctx.stroke();drawProfile();}
function drawProfile(){const c=$('profile'),g=c.getContext('2d'),w=c.clientWidth,h=c.clientHeight;g.clearRect(0,0,w,h);if(!log)return;const pts=log.points,duration=pts.at(-1).elapsed||1;g.strokeStyle='#243548';g.beginPath();g.moveTo(20,h-10);g.lineTo(w-20,h-10);g.stroke();for(const [key,col] of [['speed','#52dfb4'],['relativeAlt','#87a9ff']]){let min=Infinity,max=-Infinity;for(const p of pts)if(p[key]!==null){min=Math.min(min,p[key]);max=Math.max(max,p[key]);}if(min===Infinity)continue;g.strokeStyle=col;g.lineWidth=1.4;g.beginPath();let connected=false;for(const p of pts){if(p[key]===null){connected=false;continue;}const x=20+p.elapsed/duration*(w-40),y=h-12-(p[key]-min)/(max-min||1)*(h-25);if(!connected||p.break)g.moveTo(x,y);else g.lineTo(x,y);connected=true;}g.stroke();}const p=pts[hover>=0?hover:selected],x=20+p.elapsed/duration*(w-40);g.strokeStyle='#ffffff88';g.beginPath();g.moveTo(x,4);g.lineTo(x,h-10);g.stroke();}
function setSelected(i){selected=Math.max(0,Math.min(log.points.length-1,i));$('seek').value=selected;$('clock').textContent=`${clock(log.points[selected].elapsed)} / ${clock(log.points.at(-1).elapsed)}`;details(selected);draw();}
function stop(){playing=false;$('play').textContent='▶ 回放';}
function install(result,name){stop();log=result;selected=0;hover=-1;$('tip').hidden=true;$('empty').style.display='none';$('filename').textContent=name;$('filename').title=name;$('vehicle').value=result.vehicle;colors=new Map();for(const p of log.points)if(!colors.has(String(p.mode)))colors.set(String(p.mode),palette[colors.size%palette.length]);const pts=log.points;let distance=0,maxspeed=null;for(let i=0;i<pts.length;i++){const p=pts[i];if(p.speed!==null)maxspeed=Math.max(maxspeed??0,p.speed);if(i&&!p.break)distance+=Math.hypot(p.x-pts[i-1].x,p.y-pts[i-1].y);}$('duration').textContent=clock(pts.at(-1).elapsed);$('distance').textContent=distance>1000?`${fmt(distance/1000,2)} km`:`${fmt(distance,0)} m`;$('maxspeed').textContent=`${fmt(maxspeed)} m/s`;$('count').textContent=pts.length.toLocaleString();$('seek').max=pts.length-1;for(const id of ['play','seek','export'])$(id).disabled=false;legend();fit();setSelected(0);}
async function importFile(file){const token=++loadToken;if(worker){worker.terminate();worker=null;}stop();$('status').className='';$('status').textContent=`正在解析 ${file.name}…`;
 try{const ext=file.name.split('.').at(-1).toLowerCase();if(!['bin','json'].includes(ext))throw new Error('请导入 .BIN 或 .JSON 文件。');const buffer=await file.arrayBuffer();if(token!==loadToken)return;
 // Serialize the parser into a worker; no file:// fetch or network access required.
 const source=FlightLog.workerSource;
 let result;
 if(source&&window.Worker){const url=URL.createObjectURL(new Blob([source+'\nself.onmessage=e=>{try{const d=e.data.ext==="bin"?FlightLog.parseBin(e.data.buffer):JSON.parse(new TextDecoder().decode(e.data.buffer).replace(/^\\uFEFF/,""));self.postMessage({result:FlightLog.normalize(d)});}catch(err){self.postMessage({error:err.message});}};'],{type:'text/javascript'}));let ownWorker;try{result=await new Promise((resolve,reject)=>{ownWorker=new Worker(url);worker=ownWorker;ownWorker.onmessage=e=>e.data.error?reject(new Error(e.data.error)):resolve(e.data.result);ownWorker.onerror=()=>reject(new Error('日志解析失败。'));ownWorker.postMessage({ext,buffer},[buffer]);});}finally{ownWorker?.terminate();if(worker===ownWorker)worker=null;URL.revokeObjectURL(url);}}
 else{await new Promise(resolve=>setTimeout(resolve,30));const data=ext==='bin'?FlightLog.parseBin(buffer):JSON.parse(new TextDecoder().decode(buffer).replace(/^\uFEFF/,''));result=FlightLog.normalize(data);}
 if(token!==loadToken)return;install(result,file.name);$('status').className='success';$('status').textContent=`已读取 ${result.points.length.toLocaleString()} 个有效定位点 · GPS 实例 ${result.receiver} · ${result.vehicle==='unknown'?'机型未识别，请选择机型以显示模式名称':'已自动识别机型'}。 ${result.warnings.join(' ')}`;
 }catch(e){if(token!==loadToken)return;$('status').className='error';$('status').textContent=`导入失败：${e.message} ${log?'当前保留上一次成功导入的轨迹。':''}`;}finally{if(token===loadToken)$('file').value='';}}
$('file').onchange=e=>{if(e.target.files[0])importFile(e.target.files[0]);};
document.addEventListener('dragover',e=>{e.preventDefault();document.body.classList.add('dragging');});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('dragging');});document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('dragging');if(e.dataTransfer.files[0])importFile(e.dataTransfer.files[0]);});
$('fit').onclick=fit;$('vehicle').onchange=()=>{legend();details(hover>=0?hover:selected);$('tip').hidden=true;};
function position(e){const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
canvas.onwheel=e=>{if(!log)return;e.preventDefault();const p=position(e),old=view.scale,next=Math.max(.00001,Math.min(10000,old*Math.exp(-e.deltaY*.001)));view.cx+=(p.x-W/2)*(1/old-1/next);view.cy-=(p.y-H/2)*(1/old-1/next);view.scale=next;$('tip').hidden=true;draw();};
canvas.onpointerdown=e=>{if(!log)return;drag={...position(e),cx:view.cx,cy:view.cy,moved:false};canvas.setPointerCapture(e.pointerId);};
canvas.onpointermove=e=>{if(!log)return;const p=position(e);if(drag){if(Math.hypot(p.x-drag.x,p.y-drag.y)>3)drag.moved=true;if(drag.moved){view.cx=drag.cx-(p.x-drag.x)/view.scale;view.cy=drag.cy+(p.y-drag.y)/view.scale;hover=-1;$('tip').hidden=true;draw();}return;}
 let best=-1,dist=14;for(let i=0;i<log.points.length;i++){const a=screen(log.points[i]);const d=Math.hypot(a.x-p.x,a.y-p.y);if(d<dist){dist=d;best=i;}if(i&&!log.points[i].break){const b=screen(log.points[i-1]),dx=a.x-b.x,dy=a.y-b.y,q=Math.max(0,Math.min(1,((p.x-b.x)*dx+(p.y-b.y)*dy)/(dx*dx+dy*dy||1))),sd=Math.hypot(p.x-(b.x+q*dx),p.y-(b.y+q*dy));if(sd<dist){dist=sd;best=q<.5?i-1:i;}}}hover=best;if(best>=0){const point=log.points[best];details(best,true);const tip=$('tip');tip.replaceChildren(...[[modeName(point.mode),clock(point.elapsed)],['地速',`${fmt(point.speed)} m/s`],['海拔 / 相对高度',`${fmt(point.alt)} / ${fmt(point.relativeAlt)} m`]].map(([k,v])=>{const el=document.createElement('div');el.textContent=`${k} · ${v}`;return el;}));tip.hidden=false;tip.style.left=`${Math.max(4,Math.min(p.x+18,W-tip.offsetWidth-8))}px`;tip.style.top=`${Math.max(4,Math.min(p.y+18,H-tip.offsetHeight-8))}px`;}else{$('tip').hidden=true;details(selected);}draw();};
canvas.onpointerup=e=>{if(drag&&!drag.moved){if(hover>=0){stop();setSelected(hover);}}drag=null;canvas.releasePointerCapture(e.pointerId);};canvas.onpointercancel=()=>{drag=null;};canvas.onpointerleave=()=>{if(!drag){hover=-1;$('tip').hidden=true;if(log)details(selected);draw();}};
$('seek').oninput=e=>{stop();hover=-1;$('tip').hidden=true;setSelected(Number(e.target.value));};
$('play').onclick=()=>{if(playing){stop();return;}if(selected===log.points.length-1)setSelected(0);playing=true;hover=-1;$('tip').hidden=true;$('play').textContent='Ⅱ 暂停';playTime=log.points[selected].elapsed;lastFrame=performance.now();requestAnimationFrame(tick);};
function tick(now){if(!playing)return;playTime+=(now-lastFrame)/1000*Number($('rate').value);lastFrame=now;const pts=log.points;while(selected<pts.length-1&&pts[selected+1].elapsed<=playTime)selected++;setSelected(selected);if(playTime>=pts.at(-1).elapsed)stop();else requestAnimationFrame(tick);}
$('export').onclick=()=>{hover=-1;draw();const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height+100;const g=out.getContext('2d');g.fillStyle='#0e1823';g.fillRect(0,0,out.width,out.height);g.drawImage(canvas,0,0);g.fillStyle='#e7f0f7';g.font='14px Segoe UI';g.fillText($('filename').textContent,20,canvas.height+25);g.font='12px Segoe UI';let x=20;for(const [m,c] of colors){const label=modeName(m==='null'?null:m);g.fillStyle=c;g.fillText(`● ${label}`,x,canvas.height+52);x+=g.measureText(label).width+34;}g.fillStyle='#8eabc0';g.fillText('北向上 · 东/北米制坐标 · 起点为原点',20,canvas.height+80);out.toBlob(blob=>{const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='flight-track.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});};
$('demo').onclick=()=>{++loadToken;worker?.terminate();worker=null;const data={GPS:[],POS:[],MODE:[{TimeUS:0,ModeNum:5},{TimeUS:50000000,ModeNum:10},{TimeUS:170000000,ModeNum:11}],MSG:[{Message:'ArduPlane demo'}]};for(let i=0;i<=1000;i++){const t=i*.2,theta=i/1000*Math.PI*5,x=95*Math.sin(theta)+t*.9,y=75*(Math.cos(theta)-1);data.GPS.push({TimeUS:t*1e6,Lat:30.238+y/111195,Lng:120.042+x/96100,Status:3,Spd:14+4*Math.sin(theta),Alt:40+12*Math.sin(theta/2),NSats:19,HDop:.7});data.POS.push({TimeUS:t*1e6,RelHomeAlt:20+12*Math.sin(theta/2)});}install(FlightLog.normalize(data),'模拟示例 · 非真实飞行日志');$('status').className='';$('status').textContent='当前为模拟示例。导入真实日志后将替换此轨迹。';};
new ResizeObserver(resize).observe($('plot'));window.addEventListener('resize',resize);resize();
