'use strict';
const $=id=>document.getElementById(id), canvas=$('track'),ctx=localizedContext(canvas.getContext('2d'));
const tables={plane:{0:'MANUAL',1:'CIRCLE',2:'STABILIZE',3:'TRAINING',4:'ACRO',5:'FBWA',6:'FBWB',7:'CRUISE',8:'AUTOTUNE',10:'AUTO',11:'RTL',12:'LOITER',13:'TAKEOFF',14:'AVOID_ADSB',15:'GUIDED',17:'QSTABILIZE',18:'QHOVER',19:'QLOITER',20:'QLAND',21:'QRTL',22:'QAUTOTUNE',23:'QACRO',24:'THERMAL',25:'LOITER_ALT_QLAND',26:'AUTOLAND'},copter:{0:'STABILIZE',1:'ACRO',2:'ALT_HOLD',3:'AUTO',4:'GUIDED',5:'LOITER',6:'RTL',7:'CIRCLE',9:'LAND',11:'DRIFT',13:'SPORT',14:'FLIP',15:'AUTOTUNE',16:'POSHOLD',17:'BRAKE',18:'THROW',19:'AVOID_ADSB',20:'GUIDED_NOGPS',21:'SMART_RTL',22:'FLOWHOLD',23:'FOLLOW',24:'ZIGZAG',25:'SYSTEMID',26:'AUTOROTATE',27:'AUTO_RTL'},rover:{0:'MANUAL',1:'ACRO',3:'STEERING',4:'HOLD',5:'LOITER',6:'FOLLOW',7:'SIMPLE',10:'AUTO',11:'RTL',12:'SMART_RTL',15:'GUIDED'}};
const palette=['#52dfb4','#83a7ff','#ffbe6a','#f18bd0','#64cff0','#be9aff','#eb8585','#bada73'];
let log=null,selected=0,hover=-1,colors=new Map(),view={scale:1,cx:0,cy:0},W=1,H=1,drag=null,playing=false,lastFrame=0,playTime=0,loadToken=0,worker=null;
let rangeStart=0,rangeEnd=0,brush=null;
let profileView={start:0,end:1};
const rangePoints=()=>log?log.points.slice(rangeStart,rangeEnd+1):[];
const fmt=(n,d=1)=>n===null||n===undefined||!Number.isFinite(Number(n))?'—':Number(n).toFixed(d);
const clock=t=>{t=Math.max(0,Math.floor(t));return `${Math.floor(t/60).toString().padStart(2,'0')}:${(t%60).toString().padStart(2,'0')}`;};
const modeName=m=>m===null?t('未知模式'):tables[$('vehicle').value]?.[m]||`MODE ${String(m)}`;
const color=m=>colors.get(String(m))||'#91a9bb';
const defaultFields=[
 {id:'mode',label:'飞行模式',value:p=>modeName(p.mode)},
 {id:'time',label:'日志时间',value:p=>`${fmt(p.t,3)} s`},
 {id:'elapsed',label:'轨迹相对时间',value:p=>clock(p.elapsed)},
 {id:'speed',label:'地速',value:p=>`${fmt(p.speed)} m/s`},
 {id:'airspeed',label:'空速',value:p=>`${fmt(p.airspeed)} m/s`},
 {id:'alt',label:'GPS 海拔',value:p=>`${fmt(p.alt)} m`},
 {id:'relativeAlt',label:'相对起飞点高度',value:p=>`${fmt(p.relativeAlt)} m`},
 {id:'lat',label:'纬度',value:p=>fmt(p.lat,7)},
 {id:'lon',label:'经度',value:p=>fmt(p.lon,7)},
 {id:'attitude',label:'横滚 / 俯仰',value:p=>`${fmt(p.roll)}° / ${fmt(p.pitch)}°`},
 {id:'gpsquality',label:'卫星数 / HDOP',value:p=>`${fmt(p.satellites,0)} / ${fmt(p.hdop,2)}`},
 {id:'voltage',label:'电池电压',value:p=>`${fmt(p.voltage,2)} V`}
];
const preferenceKey='flight-log-explorer.fields.v1';
let chosen=new Set(defaultFields.map(f=>f.id)),fieldCatalog=[...defaultFields];
try{const saved=JSON.parse(localStorage.getItem(preferenceKey));if(Array.isArray(saved)&&saved.every(x=>typeof x==='string'))chosen=new Set(saved);}catch{}
const fieldNames={
 'GPS.Spd':['地速','m/s'],'GPS.Alt':['GPS 海拔','m'],'GPS.NSats':['卫星数','颗'],'GPS.HDop':['HDOP',''],
 'POS.Alt':['估算海拔','m'],'POS.RelHomeAlt':['相对起飞点高度','m'],'POS.RelOriginAlt':['相对原点高度','m'],
 'ATT.Roll':['横滚','°'],'ATT.Pitch':['俯仰','°'],'BAT.Volt':['电池电压','V'],
 'CTUN.NavRoll':['导航目标横滚','°'],'CTUN.NavPitch':['导航目标俯仰','°'],'CTUN.Roll':['控制横滚','°'],'CTUN.Pitch':['控制俯仰','°'],'CTUN.As':['估算空速','m/s'],
 'GPS.GCrs':['航迹方向','°'],'GPS.VZ':['GPS 垂直速度','m/s'],'GPS.Status':['GPS 定位状态',''],'GPS.Yaw':['GPS 航向','°'],
 'ATT.Yaw':['航向','°'],'ATT.DesRoll':['目标横滚','°'],'ATT.DesPitch':['目标俯仰','°'],'ATT.DesYaw':['目标航向','°'],
 'CTUN.ThO':['油门输出','%'],'CTUN.ThD':['油门需求',''],'CTUN.RdO':['方向舵输出',''],'CTUN.AsT':['空速估算类型',''],
 'BAT.Curr':['电流','A'],'BAT.CurrTot':['累计耗电量','mAh'],'BAT.EnrgTot':['累计耗能','Wh'],'BAT.RemPct':['剩余电量','%'],'BAT.Temp':['电池温度','°C'],
 'VIBE.VibeX':['X 轴振动','m/s²'],'VIBE.VibeY':['Y 轴振动','m/s²'],'VIBE.VibeZ':['Z 轴振动','m/s²'],'VIBE.Clip':['加速度计削顶计数',''],
 'NTUN.Dist':['距目标点距离','m'],'NTUN.XT':['横向偏差','m'],'NTUN.AltE':['高度误差','m'],'NTUN.AsE':['空速误差','m/s'],
 'NTUN.TAsp':['目标空速','m/s'],'NTUN.TAW':['航点目标高度','m'],'NTUN.TAT':['TECS 目标高度','m'],
 'TECS.h':['TECS 高度','m'],'TECS.hdem':['TECS 目标高度','m'],'TECS.sp':['TECS 空速','m/s'],'TECS.spdem':['TECS 目标空速','m/s'],'TECS.dh':['TECS 爬升率','m/s'],
 'STAT.Armed':['解锁状态',''],'STAT.isFlying':['飞行状态',''],'STAT.Stage':['飞行阶段',''],'STAT.Crash':['坠机状态',''],
 'MODE.Rsn':['模式切换原因',''],'MSG.Message':['最近文字消息',''],'MSG.Msg':['最近文字消息',''],
 'AOA.AOA':['估算迎角','°'],'AOA.SSA':['估算侧滑角','°'],
 'BARO.Alt':['气压高度','m'],'BARO.Temp':['气压计温度','°C'],'TERR.TerrH':['地形高度','m'],'TERR.CHeight':['估算离地高度','m'],
 'GPA.HAcc':['GPS 水平精度','m'],'GPA.VAcc':['GPS 垂直精度','m'],'GPA.SAcc':['GPS 速度精度','m/s']
};
function buildFieldCatalog(){fieldCatalog=[...defaultFields];if(!log)return;
 const redundant={GPS:['Lat','Lng','Spd','Alt','NSats','HDop'],MODE:['Mode','ModeNum'],POS:['RelHomeAlt'],ATT:['Roll','Pitch'],BAT:['Volt'],CTUN:['As'],ARSP:['Airspeed']};
 for(const [streamId,stream] of Object.entries(log.streams||{}).sort(([a],[b])=>a.localeCompare(b))){
  const keys=new Set();for(const r of stream.rows)for(const [k,v] of Object.entries(r))if(!['t','TimeUS','TimeMS',stream.instanceKey].includes(k)&&(typeof v==='number'||typeof v==='string'))keys.add(k);
  for(const key of keys){if(redundant[stream.type]?.includes(key)&&(stream.instance===null||Number(stream.instance)===0||stream.type==='GPS'&&Number(stream.instance)===log.receiver))continue;
   const source=`${stream.type}.${key}`,spec=fieldNames[source],suffix=stream.instanceKey?` · ${stream.instanceKey}=${stream.instance}`:'';
   fieldCatalog.push({id:`raw:${streamId}:${key}`,label:(spec?.[0]||source)+suffix,source,group:stream.type,value:p=>{const row=FlightLog.latest(stream.rows,p.t,stream.type==='MODE'?Infinity:2),v=row?.[key];return v===null||v===undefined?'—':(typeof v==='number'?(Number.isFinite(v)?Number(v.toFixed(5)).toString():'—'):String(v))+(spec?.[1]?` ${t(spec[1])}`:'');}});
  }
 }
}
function rows(p,includeMode=false){return fieldCatalog.filter(f=>chosen.has(f.id)&&(includeMode||f.id!=='mode')).map(f=>[t(f.label),f.value(p)]);}
function details(i,isHover=false){if(!log)return;const p=log.points[i];$('modebadge').hidden=!chosen.has('mode');$('modebadge').textContent=modeName(p.mode);$('modebadge').style.color=color(p.mode);$('pointstate').textContent=isHover?'悬停位置':`定位点 ${i+1}`;const values=rows(p);$('details').replaceChildren(...values.map(([k,v])=>{const el=document.createElement('div');el.className='data-row';const a=document.createElement('span'),b=document.createElement('strong');a.textContent=k;b.textContent=v;el.append(a,b);return el;}));if(!values.length&&!chosen.has('mode'))$('details').textContent='未选择显示信息，请点击「显示信息」勾选。';}
function renderFieldOptions(){const query=$('field-search').value.trim().toLowerCase(),container=$('field-options');container.replaceChildren();const groups=new Map();for(const f of fieldCatalog){if(query&&!`${f.label} ${t(f.label)} ${f.source||''}`.toLowerCase().includes(query))continue;const group=f.group||'默认信息';if(!groups.has(group)){const section=document.createElement('fieldset'),title=document.createElement('legend');title.textContent=group;section.append(title);groups.set(group,section);container.append(section);}const label=document.createElement('label'),input=document.createElement('input'),name=document.createElement('span');input.type='checkbox';input.value=f.id;input.checked=chosen.has(f.id);name.textContent=f.label;label.append(input,name);if(f.source){const source=document.createElement('small');source.textContent=f.source;label.append(source);}input.onchange=()=>{if(input.checked)chosen.add(f.id);else chosen.delete(f.id);saveFieldSelection();};groups.get(group).append(label);}if(!groups.size)container.textContent='没有匹配字段。';updateFieldCount();}
function updateFieldCount(){$('field-count').textContent=`已选 ${fieldCatalog.filter(f=>chosen.has(f.id)).length} / ${fieldCatalog.length} 项`;}
function saveFieldSelection(){try{localStorage.setItem(preferenceKey,JSON.stringify([...chosen]));}catch{}updateFieldCount();$('tip').hidden=true;if(log)details(hover>=0?hover:selected,hover>=0);}
$('fields').onclick=()=>{renderFieldOptions();$('field-dialog').showModal();};$('field-close').onclick=()=>$('field-dialog').close();$('field-search').oninput=renderFieldOptions;
$('field-default').onclick=()=>{chosen=new Set(defaultFields.map(f=>f.id));saveFieldSelection();renderFieldOptions();};$('field-clear').onclick=()=>{chosen.clear();saveFieldSelection();renderFieldOptions();};
function legend(){const modes=new Set(rangePoints().map(p=>String(p.mode))); $('legend').replaceChildren(...[...colors].filter(([m])=>modes.has(m)).map(([m,c])=>{const el=document.createElement('span'),dot=document.createElement('i');dot.style.background=c;el.append(dot,document.createTextNode(modeName(m==='null'?null:m)));return el;}));}
function screen(p){return {x:W/2+(p.x-view.cx)*view.scale,y:H/2-(p.y-view.cy)*view.scale};}
function fit(){if(!log)return;const xs=rangePoints().map(p=>p.x),ys=rangePoints().map(p=>p.y);let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const x of xs){minX=Math.min(minX,x);maxX=Math.max(maxX,x);}for(const y of ys){minY=Math.min(minY,y);maxY=Math.max(maxY,y);}view={cx:(minX+maxX)/2,cy:(minY+maxY)/2,scale:Math.min((W-120)/Math.max(20,maxX-minX),(H-120)/Math.max(20,maxY-minY))};draw();}
function size(c){const r=c.getBoundingClientRect(),dpr=window.devicePixelRatio||1;c.width=Math.round(r.width*dpr);c.height=Math.round(r.height*dpr);const cctx=localizedContext(c.getContext('2d'));cctx.setTransform(dpr,0,0,dpr,0,0);return {w:r.width,h:r.height};}
function resize(){const s=size(canvas);W=s.w;H=s.h;size($('profile'));if(log)fit();else draw();}
function draw(){ctx.fillStyle='#0e1823';ctx.fillRect(0,0,W,H);const ideal=90/view.scale,power=10**Math.floor(Math.log10(ideal)),step=([1,2,5,10].find(n=>n*power>=ideal)||10)*power;ctx.lineWidth=1;ctx.strokeStyle='#203043';ctx.fillStyle='#5f7d92';ctx.font='10px Segoe UI';const x0=view.cx-W/(2*view.scale),y0=view.cy-H/(2*view.scale);for(let x=Math.ceil(x0/step)*step;x<x0+W/view.scale;x+=step){const s=screen({x,y:0});ctx.beginPath();ctx.moveTo(s.x,0);ctx.lineTo(s.x,H);ctx.stroke();ctx.fillText(`${Math.round(x)} E`,s.x+5,H-39);}for(let y=Math.ceil(y0/step)*step;y<y0+H/view.scale;y+=step){const s=screen({x:0,y});ctx.beginPath();ctx.moveTo(0,s.y);ctx.lineTo(W,s.y);ctx.stroke();ctx.fillText(`${Math.round(y)} N`,8,s.y-5);}if(!log)return;
 const pts=log.points;ctx.lineWidth=2.6;ctx.lineJoin='round';ctx.lineCap='round';for(let i=rangeStart+1;i<=rangeEnd;i++){if(pts[i].break)continue;const a=screen(pts[i-1]),b=screen(pts[i]);ctx.strokeStyle=color(pts[i-1].mode);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
 function marker(p,c,label){const s=screen(p);ctx.fillStyle=c;ctx.beginPath();ctx.arc(s.x,s.y,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e7f0f7';ctx.fillText(label,s.x+9,s.y-9);}marker(pts[rangeStart],'#52dfb4',rangeStart?'区间起点':'起点');marker(pts[rangeEnd],'#ffbe6a',rangeEnd<pts.length-1?'区间终点':'终点');
 const p=screen(pts[hover>=0?hover:selected]);ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.fillStyle=color(pts[hover>=0?hover:selected].mode);ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.fill();ctx.stroke();drawProfile();}
// Keep fractional CSS dimensions consistent with pointer hit testing (clientWidth rounds).
function profileX(elapsed){return 20+(elapsed-profileView.start)/(profileView.end-profileView.start)*($('profile').getBoundingClientRect().width-40);}
function profileTime(x){return profileView.start+(x-20)/($('profile').clientWidth-40)*(profileView.end-profileView.start);}
function resetProfileZoom(){profileView={start:0,end:log?.points.at(-1).elapsed||1};$('profile-zoom-reset').disabled=true;drawProfile();}
function drawProfile(){const c=$('profile'),g=localizedContext(c.getContext('2d')),w=c.getBoundingClientRect().width,h=c.getBoundingClientRect().height;g.clearRect(0,0,w,h);if(!log)return;g.save();g.beginPath();g.rect(20,0,w-40,h-20);g.clip();const pts=log.points;g.strokeStyle='#243548';g.beginPath();g.moveTo(20,h-20);g.lineTo(w-20,h-20);g.stroke();for(const [key,col] of [['speed','#52dfb4'],['relativeAlt','#87a9ff']]){let min=Infinity,max=-Infinity;for(const p of pts)if(p[key]!==null){min=Math.min(min,p[key]);max=Math.max(max,p[key]);}if(min===Infinity)continue;g.strokeStyle=col;g.lineWidth=1.4;g.beginPath();let connected=false;for(const p of pts){if(p[key]===null){connected=false;continue;}const x=profileX(p.elapsed),y=h-22-(p[key]-min)/(max-min||1)*(h-35);if(!connected||p.break)g.moveTo(x,y);else g.lineTo(x,y);connected=true;}g.stroke();}
 const left=brush?.left??profileX(log.points[rangeStart].elapsed),right=brush?.right??profileX(log.points[rangeEnd].elapsed);g.fillStyle='#050b1333';g.fillRect(20,0,Math.max(0,left-20),h-20);g.fillRect(right,0,Math.max(0,w-20-right),h-20);g.fillStyle='#52dfb415';g.fillRect(left,0,Math.max(1,right-left),h-20);g.strokeStyle='#52dfb4';g.lineWidth=1;g.strokeRect(left+.5,1,Math.max(1,right-left-1),h-22);for(const x of [left,right]){g.fillStyle='#52dfb4';g.fillRect(x-3,(h-20)/2-10,6,20);}
 const p=log.points[hover>=0?hover:selected],x=profileX(p.elapsed);g.strokeStyle='#ffffff88';g.beginPath();g.moveTo(x,4);g.lineTo(x,h-20);g.stroke();g.fillStyle='#d9e5ed';g.beginPath();g.moveTo(x-5,4);g.lineTo(x+5,4);g.lineTo(x,11);g.closePath();g.fill();g.restore();g.fillStyle='#8eabc0';g.font='10px Segoe UI';const span=profileView.end-profileView.start;for(let k=0;k<=4;k++){const time=profileView.start+k/4*span;g.textAlign=k===0?'left':k===4?'right':'center';g.fillText(span<10?fmt(time,1)+' s':clock(time),20+k/4*(w-40),h-4);}g.textAlign='left';}
function setSelected(i){selected=Math.max(rangeStart,Math.min(rangeEnd,i));$('seek').value=selected;$('clock').textContent=`${clock(log.points[selected].elapsed)} / ${clock(log.points[rangeEnd].elapsed)}`;details(selected);draw();}
function nearestIndex(t){const pts=log.points;let lo=0,hi=pts.length;while(lo<hi){const mid=(lo+hi)>>1;if(pts[mid].elapsed<t)lo=mid+1;else hi=mid;}if(!lo)return 0;if(lo===pts.length)return lo-1;return t-pts[lo-1].elapsed<=pts[lo].elapsed-t?lo-1:lo;}
function updateRangeSummary(){const pts=rangePoints();let distance=0,maxspeed=null;for(let i=0;i<pts.length;i++){const p=pts[i];if(p.speed!==null)maxspeed=Math.max(maxspeed??0,p.speed);if(i&&!p.break)distance+=Math.hypot(p.x-pts[i-1].x,p.y-pts[i-1].y);}$('duration').textContent=clock(pts.at(-1).elapsed-pts[0].elapsed);$('distance').textContent=distance>1000?`${fmt(distance/1000,2)} km`:`${fmt(distance,0)} m`;$('maxspeed').textContent=`${fmt(maxspeed)} m/s`;$('count').textContent=pts.length.toLocaleString();$('seek').min=rangeStart;$('seek').max=rangeEnd;const full=rangeStart===0&&rangeEnd===log.points.length-1;$('range-label').textContent=`${full?'全选':'当前范围'} · ${clock(pts[0].elapsed)} – ${clock(pts.at(-1).elapsed)} · ${pts.length.toLocaleString()} 点`;$('range-reset').disabled=full;for(const [id,p] of [['range-from',pts[0]],['range-to',pts.at(-1)]]){$(id).disabled=false;$(id).max=log.points.at(-1).elapsed;$(id).value=fmt(p.elapsed,3);}legend();}
function applyRange(a,b){if(!log)return;stop();rangeStart=Math.max(0,Math.min(log.points.length-1,Math.min(a,b)));rangeEnd=Math.max(rangeStart,Math.min(log.points.length-1,Math.max(a,b)));hover=-1;$('tip').hidden=true;brush=null;updateRangeSummary();selected=Math.max(rangeStart,Math.min(rangeEnd,selected));fit();setSelected(selected);refreshChart();}
const profile=$('profile');
function profilePosition(e){const r=profile.getBoundingClientRect();return Math.max(20,Math.min(r.width-20,e.clientX-r.left));}
function profileIndex(x){return nearestIndex(profileTime(x));}
const profileHandleRadius=10; // CSS pixels, measured from the visible left/right edges.
function profileHandle(e){if(!log)return null;const r=profile.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(y<0||y>r.height-20)return null;const left=profileX(log.points[rangeStart].elapsed),right=profileX(log.points[rangeEnd].elapsed),dl=left>=20&&left<=r.width-20?Math.abs(x-left):Infinity,dr=right>=20&&right<=r.width-20?Math.abs(x-right):Infinity;if(Math.min(dl,dr)>profileHandleRadius)return null;return left===right?'both':dl===dr?(x<=(left+right)/2?'left':'right'):dl<dr?'left':'right';}
function profileTarget(e){if(!log)return null;const r=profile.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(y<0||y>r.height-20)return null;const edge=profileHandle(e),cursor=profileX(log.points[hover>=0?hover:selected].elapsed);if(cursor>=20&&cursor<=r.width-20&&Math.abs(x-cursor)<=8&&(!edge||y<=18))return 'seek';return edge;}
profile.onpointerdown=e=>{if(!log||e.button!==0)return;if(['range-from','range-to'].includes(document.activeElement?.id))document.activeElement.blur();const mode=profileTarget(e);if(!mode)return;stop();const x=profilePosition(e),left=profileX(log.points[rangeStart].elapsed),right=profileX(log.points[rangeEnd].elapsed),point=hover>=0?hover:selected;hover=-1;$('tip').hidden=true;brush={origin:x,left,right,mode,moved:false,cursorX:profileX(log.points[point].elapsed)};if(mode==='seek')setSelected(point);profile.style.cursor=mode==='seek'?'grabbing':'ew-resize';profile.setPointerCapture(e.pointerId);};
profile.onpointermove=e=>{if(!brush){const target=profileTarget(e);profile.style.cursor=target==='seek'?'grab':target?'ew-resize':'default';return;}const x=profilePosition(e);if(Math.abs(x-brush.origin)>3)brush.moved=true;if(!brush.moved)return;if(brush.mode==='seek'){setSelected(profileIndex(brush.cursorX+x-brush.origin));return;}if(brush.mode==='both')brush.mode=x<brush.origin?'left':'right';if(brush.mode==='left')brush.left=Math.min(x,brush.right);else brush.right=Math.max(x,brush.left);drawProfile();};
profile.onpointerup=e=>{if(!brush)return;const selection=brush;brush=null;if(selection.mode==='seek'){if(selection.moved)setSelected(profileIndex(selection.cursorX+profilePosition(e)-selection.origin));}else if(selection.moved)applyRange(profileIndex(selection.left),profileIndex(selection.right));else setSelected(profileIndex(profilePosition(e)));profile.releasePointerCapture(e.pointerId);const target=profileTarget(e);profile.style.cursor=target==='seek'?'grab':target?'ew-resize':'default';drawProfile();};
profile.onpointercancel=()=>{brush=null;profile.style.cursor='default';drawProfile();};profile.onpointerleave=()=>{if(!brush)profile.style.cursor='default';};profile.ondblclick=()=>{if(log)applyRange(0,log.points.length-1);};
profile.addEventListener('wheel',e=>{if(!e.ctrlKey||!log)return;e.preventDefault();if(brush)return;const total=log.points.at(-1).elapsed;if(total<=0)return;const r=profile.getBoundingClientRect(),fraction=(profilePosition(e)-20)/(r.width-40),span=profileView.end-profileView.start,anchor=profileView.start+fraction*span,delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?r.height:1),next=Math.max(Math.min(total,.2),total/200,Math.min(total,span*Math.exp(Math.max(-4,Math.min(4,delta*.002)))));const start=Math.max(0,Math.min(total-next,anchor-fraction*next));profileView={start,end:start+next};$('profile-zoom-reset').disabled=next>=total;drawProfile();const target=profileTarget(e);profile.style.cursor=target==='seek'?'grab':target?'ew-resize':'default';},{passive:false});
$('profile-zoom-reset').onclick=resetProfileZoom;
$('range-reset').onclick=()=>applyRange(0,log.points.length-1);
$('range-from').onchange=()=>{if(log){const value=$('range-from').valueAsNumber;if(Number.isFinite(value))applyRange(Math.min(nearestIndex(value),rangeEnd),rangeEnd);else updateRangeSummary();}};
$('range-to').onchange=()=>{if(log){const value=$('range-to').valueAsNumber;if(Number.isFinite(value))applyRange(rangeStart,Math.max(rangeStart,nearestIndex(value)));else updateRangeSummary();}};
function stop(){playing=false;$('play').textContent='▶ 回放';}
function install(result,name){stop();log=result;selected=0;hover=-1;$('tip').hidden=true;$('empty').style.display='none';$('filename').textContent=name;$('filename').title=name;$('vehicle').value=result.vehicle;buildFieldCatalog();colors=new Map();for(const p of log.points)if(!colors.has(String(p.mode)))colors.set(String(p.mode),palette[colors.size%palette.length]);rangeStart=0;rangeEnd=log.points.length-1;brush=null;resetProfileZoom();for(const id of ['play','seek','export'])$(id).disabled=false;updateRangeSummary();fit();setSelected(0);refreshChart(true);}
async function importFile(file){const token=++loadToken;if(worker){worker.terminate();worker=null;}stop();$('status').className='';$('status').textContent=`正在解析 ${file.name}…`;
 try{const ext=file.name.split('.').at(-1).toLowerCase();if(!['bin','json'].includes(ext))throw new Error('请导入 .BIN 或 .JSON 文件。');const buffer=await file.arrayBuffer();if(token!==loadToken)return;
 // Serialize the parser into a worker; no file:// fetch or network access required.
 const source=FlightLog.workerSource;
 let result;
 if(source&&window.Worker){const url=URL.createObjectURL(new Blob([source+'\nself.onmessage=e=>{try{const d=e.data.ext==="bin"?FlightLog.parseBin(e.data.buffer):JSON.parse(new TextDecoder().decode(e.data.buffer).replace(/^\\uFEFF/,""));self.postMessage({result:FlightLog.normalize(d)});}catch(err){self.postMessage({error:err.message});}};'],{type:'text/javascript'}));let ownWorker;try{result=await new Promise((resolve,reject)=>{ownWorker=new Worker(url);worker=ownWorker;ownWorker.onmessage=e=>e.data.error?reject(new Error(e.data.error)):resolve(e.data.result);ownWorker.onerror=()=>reject(new Error('日志解析失败。'));ownWorker.postMessage({ext,buffer},[buffer]);});}finally{ownWorker?.terminate();if(worker===ownWorker)worker=null;URL.revokeObjectURL(url);}}
 else{await new Promise(resolve=>setTimeout(resolve,30));const data=ext==='bin'?FlightLog.parseBin(buffer):JSON.parse(new TextDecoder().decode(buffer).replace(/^\uFEFF/,''));result=FlightLog.normalize(data);}
 if(token!==loadToken)return;install(result,file.name);$('status').className='success';$('status').textContent=`已读取 ${result.points.length.toLocaleString()} 个有效定位点 · GPS 实例 ${result.receiver} · ${result.vehicle==='unknown'?'机型未识别，请选择机型以显示模式名称':'已自动识别机型'}。 ${result.warnings.join(' ')}`;
 }catch(e){if(token!==loadToken)return;$('status').className='error';$('status').textContent=`导入失败：${e.message} ${log?'当前保留上一次成功导入的轨迹。':''}`;}finally{if(token===loadToken)$('file').value='';}}
$('file').onchange=e=>{if(e.target.files[0])importFile(e.target.files[0]);};
document.addEventListener('dragover',e=>{e.preventDefault();document.body.classList.add('dragging');});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('dragging');});document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('dragging');if(e.dataTransfer.files[0])importFile(e.dataTransfer.files[0]);});
$('fit').onclick=fit;$('vehicle').onchange=()=>{legend();details(hover>=0?hover:selected);$('tip').hidden=true;};
function position(e){const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
canvas.onwheel=e=>{if(!log)return;e.preventDefault();const p=position(e),old=view.scale,next=Math.max(.00001,Math.min(10000,old*Math.exp(-e.deltaY*.001)));view.cx+=(p.x-W/2)*(1/old-1/next);view.cy-=(p.y-H/2)*(1/old-1/next);view.scale=next;$('tip').hidden=true;draw();};
canvas.onpointerdown=e=>{if(!log)return;drag={...position(e),cx:view.cx,cy:view.cy,moved:false};canvas.setPointerCapture(e.pointerId);};
canvas.onpointermove=e=>{if(!log)return;const p=position(e);if(drag){if(Math.hypot(p.x-drag.x,p.y-drag.y)>3)drag.moved=true;if(drag.moved){view.cx=drag.cx-(p.x-drag.x)/view.scale;view.cy=drag.cy+(p.y-drag.y)/view.scale;hover=-1;$('tip').hidden=true;draw();}return;}
 let best=-1,dist=14;for(let i=rangeStart;i<=rangeEnd;i++){const a=screen(log.points[i]);const d=Math.hypot(a.x-p.x,a.y-p.y);if(d<dist){dist=d;best=i;}if(i>rangeStart&&!log.points[i].break){const b=screen(log.points[i-1]),dx=a.x-b.x,dy=a.y-b.y,q=Math.max(0,Math.min(1,((p.x-b.x)*dx+(p.y-b.y)*dy)/(dx*dx+dy*dy||1))),sd=Math.hypot(p.x-(b.x+q*dx),p.y-(b.y+q*dy));if(sd<dist){dist=sd;best=q<.5?i-1:i;}}}hover=best;if(best>=0){const point=log.points[best];details(best,true);const tip=$('tip');tip.replaceChildren(...(rows(point,true).length?rows(point,true):[[t('提示'),t('未选择显示信息')]]).map(([k,v])=>{const el=document.createElement('div');el.textContent=`${k} · ${v}`;return el;}));tip.hidden=false;tip.style.left=`${Math.max(4,Math.min(p.x+18,W-tip.offsetWidth-8))}px`;tip.style.top=`${Math.max(4,Math.min(p.y+18,H-tip.offsetHeight-8))}px`;}else{$('tip').hidden=true;details(selected);}draw();};
canvas.onpointerup=e=>{if(drag&&!drag.moved){if(hover>=0){stop();setSelected(hover);}}drag=null;canvas.releasePointerCapture(e.pointerId);};canvas.onpointercancel=()=>{drag=null;};canvas.onpointerleave=e=>{if($('tip').contains(e.relatedTarget))return;if(!drag){hover=-1;$('tip').hidden=true;if(log)details(selected);draw();}};
$('tip').onpointerleave=e=>{if(e.relatedTarget===canvas)return;hover=-1;$('tip').hidden=true;if(log)details(selected);draw();};
$('seek').oninput=e=>{stop();hover=-1;$('tip').hidden=true;setSelected(Number(e.target.value));};
$('play').onclick=()=>{if(playing){stop();return;}if(selected===rangeEnd)setSelected(rangeStart);playing=true;hover=-1;$('tip').hidden=true;$('play').textContent='Ⅱ 暂停';playTime=log.points[selected].elapsed;lastFrame=performance.now();requestAnimationFrame(tick);};
function tick(now){if(!playing)return;playTime+=(now-lastFrame)/1000*Number($('rate').value);lastFrame=now;const pts=log.points;while(selected<rangeEnd&&pts[selected+1].elapsed<=playTime)selected++;setSelected(selected);if(playTime>=pts[rangeEnd].elapsed)stop();else requestAnimationFrame(tick);}
$('export').onclick=()=>{hover=-1;draw();const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height+100;const g=localizedContext(out.getContext('2d'));g.fillStyle='#0e1823';g.fillRect(0,0,out.width,out.height);g.drawImage(canvas,0,0);g.fillStyle='#e7f0f7';g.font='14px Segoe UI';g.fillText($('filename').textContent,20,canvas.height+25);g.font='12px Segoe UI';let x=20;for(const [m,c] of colors){if(!rangePoints().some(p=>String(p.mode)===m))continue;const label=modeName(m==='null'?null:m);g.fillStyle=c;g.fillText(`● ${label}`,x,canvas.height+52);x+=g.measureText(label).width+34;}g.fillStyle='#8eabc0';g.fillText(`北向上 · 东/北米制坐标 · 范围 ${clock(log.points[rangeStart].elapsed)} – ${clock(log.points[rangeEnd].elapsed)}`,20,canvas.height+80);out.toBlob(blob=>{const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='flight-track.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});};
$('demo').onclick=()=>{++loadToken;worker?.terminate();worker=null;const data=createDemoLog();install(FlightLog.normalize(data),'模拟示例 · 非真实飞行日志');$('status').className='';$('status').textContent='当前为模拟示例。导入真实日志后将替换此轨迹。';};
new ResizeObserver(resize).observe($('plot'));window.addEventListener('resize',resize);resize();
