'use strict';
let chartCatalog=[],chartSelections=['speed','relativeAlt'],chartRendered=null;
const chartCanvas=$('parameter-chart');
const baseChartFields=[['speed','地速','m/s'],['airspeed','空速','m/s'],['alt','GPS 海拔','m'],['relativeAlt','相对起飞点高度','m'],['roll','横滚','°'],['pitch','俯仰','°'],['voltage','电池电压','V'],['satellites','卫星数','颗'],['hdop','HDOP','']];
function buildChartCatalog(){chartCatalog=baseChartFields.map(([id,label,unit])=>({id,label,unit,group:'常用参数',samples:()=>log.points.map(p=>({t:p.t,v:p[id],break:p.break}))}));
 for(const [streamId,stream] of Object.entries(log.streams||{}).sort(([a],[b])=>a.localeCompare(b))){const keys=new Set();for(const row of stream.rows)for(const [key,value] of Object.entries(row))if(!['t','TimeUS','TimeMS',stream.instanceKey].includes(key)&&typeof value==='number'&&Number.isFinite(value))keys.add(key);
  for(const key of keys){const source=`${stream.type}.${key}`,spec=fieldNames[source],suffix=stream.instanceKey?` · ${stream.instanceKey}=${stream.instance}`:'';chartCatalog.push({id:`raw:${streamId}:${key}`,label:(spec?.[0]||source)+suffix,unit:spec?spec[1]:`原始值 (${source})`,group:stream.type,samples:()=>stream.rows.map(r=>({t:r.t,v:r[key]}))});}
 }
}
function refreshChart(newLog=false){if(!log)return;if(newLog){buildChartCatalog();chartSelections=chartSelections.filter(id=>chartCatalog.some(f=>f.id===id));if(!chartSelections.length)chartSelections=['speed','relativeAlt'];renderChartControls();}for(const id of ['chart-add','chart-generate'])$(id).disabled=false;$('chart-add').disabled=chartSelections.length>=6;generateChart();}
function renderChartControls(){const container=$('chart-series');container.replaceChildren();chartSelections.forEach((id,i)=>{const row=document.createElement('div');row.className='chart-series-row';const dot=document.createElement('i');dot.style.background=palette[i];const select=document.createElement('select');select.setAttribute('aria-label',`纵轴参数 ${i+1}`);const groups=new Map();for(const f of chartCatalog){if(!groups.has(f.group)){const group=document.createElement('optgroup');group.label=f.group;groups.set(f.group,group);select.append(group);}const option=document.createElement('option');option.value=f.id;option.textContent=`${f.label} [${f.unit||'无量纲'}]`;groups.get(f.group).append(option);}select.value=id;select.onchange=()=>{chartSelections[i]=select.value;generateChart();};const remove=document.createElement('button');remove.textContent='移除';remove.setAttribute('aria-label',`移除参数 ${i+1}`);remove.onclick=()=>{chartSelections.splice(i,1);renderChartControls();generateChart();};row.append(dot,select,remove);container.append(row);});$('chart-add').disabled=!log||chartSelections.length>=6;}
function chartWindow(){const pts=log.points;return $('chart-scope').value==='full'?{start:pts[0].t,end:pts.at(-1).t}:{start:pts[rangeStart].t,end:pts[rangeEnd].t};}
function generateChart(){if(!log)return;const window=chartWindow(),origin=log.points[0].t,series=chartSelections.map((id,i)=>{const f=chartCatalog.find(f=>f.id===id);return {...f,color:palette[i],samples:f.samples().filter(p=>p.t>=window.start&&p.t<=window.end)};});const normalized=$('chart-scale').value==='normalized',axes=new Map();for(const s of series){const values=s.samples.map(p=>p.v).filter(v=>typeof v==='number'&&Number.isFinite(v));s.min=Infinity;s.max=-Infinity;for(const v of values){s.min=Math.min(s.min,v);s.max=Math.max(s.max,v);}s.count=values.length;s.axis=normalized?s.id:s.unit||'无量纲';if(!axes.has(s.axis))axes.set(s.axis,{unit:normalized?'归一化 %':s.unit||'无量纲',min:Infinity,max:-Infinity,color:s.color});if(s.count){const axis=axes.get(s.axis);axis.min=Math.min(axis.min,s.min);axis.max=Math.max(axis.max,s.max);}}
 for(const axis of axes.values()){if(axis.min===Infinity){axis.min=0;axis.max=1;}const padding=(axis.max-axis.min||Math.max(1,Math.abs(axis.min)*.1))*.08;axis.low=axis.min-padding;axis.high=axis.max+padding;}
 chartRendered={...window,origin,series,axes,normalized};$('chart-status').textContent=series.length?`${$('chart-scope').value==='full'?'完整日志':'当前框选范围'} · ${clock(window.start-origin)} – ${clock(window.end-origin)} · ${series.filter(s=>s.count).length}/${series.length} 条曲线有数据${series.some(s=>!s.count)?'；缺失参数已在图例标注':''}`:'请添加至少一个纵轴参数。';$('chart-download').disabled=!series.some(s=>s.count);renderChartLegend();drawParameterChart();}
function renderChartLegend(){$('chart-legend').replaceChildren(...chartRendered.series.map(s=>{const el=document.createElement('span'),dot=document.createElement('i');dot.style.background=s.color;el.append(dot,document.createTextNode(`${s.label} · ${s.count?`${s.count.toLocaleString()} 点 · ${fmt(s.min,2)} – ${fmt(s.max,2)} ${s.unit}`:'此范围无数据'}`));return el;}));}
function drawParameterChart(){const axes=chartRendered?[...chartRendered.axes.values()]:[],normalized=chartRendered?.normalized;const axisCount=normalized?1:Math.max(1,axes.length);chartCanvas.style.minWidth=`${Math.max(680,440+axisCount*88)}px`;const width=Math.max(chartCanvas.parentElement.clientWidth,parseInt(chartCanvas.style.minWidth)),height=400,dpr=window.devicePixelRatio||1;chartCanvas.style.width=`${width}px`;chartCanvas.width=width*dpr;chartCanvas.height=height*dpr;const g=chartCanvas.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.fillStyle='#0e1823';g.fillRect(0,0,width,height);g.fillStyle='#e7f0f7';g.font='15px Segoe UI, Microsoft YaHei';g.fillText('飞行参数 · 时间曲线',20,26);if(!chartRendered){g.fillStyle='#8eabc0';g.fillText('导入日志后生成图像',30,110);return;}
 const r=chartRendered,left=68,right=width-22-(axisCount-1)*88,top=72,bottom=350,span=r.end-r.start||1;const x=t=>left+(t-r.start)/span*(right-left);g.font='11px Segoe UI, Microsoft YaHei';g.fillStyle='#8eabc0';g.fillText(`${$('filename').textContent} · ${clock(r.start-r.origin)} – ${clock(r.end-r.origin)}`,20,47);
 for(let k=0;k<=5;k++){const py=top+k/5*(bottom-top);g.strokeStyle='#243548';g.beginPath();g.moveTo(left,py);g.lineTo(right,py);g.stroke();const tx=left+k/5*(right-left);g.beginPath();g.moveTo(tx,top);g.lineTo(tx,bottom);g.stroke();g.fillStyle='#8eabc0';g.textAlign='center';g.fillText(fmt(r.start-r.origin+k/5*(r.end-r.start),1),tx,bottom+22);}g.fillText('相对时间 (s)',(left+right)/2,height-13);g.textAlign='left';
 const displayAxes=normalized?[{unit:'归一化 %',low:0,high:100,color:'#8eabc0'}]:axes;displayAxes.forEach((axis,i)=>{const ax=i===0?left:right+(i-1)*88;g.strokeStyle=axis.color;g.beginPath();g.moveTo(ax,top);g.lineTo(ax,bottom);g.stroke();g.fillStyle=axis.color;g.textAlign=i===0?'right':'left';const offset=i===0?-8:8;const unit=axis.unit.length>13?axis.unit.slice(0,12)+'…':axis.unit;g.fillText(unit,ax+offset,top-13);for(let k=0;k<=5;k++)g.fillText(fmt(axis.high-k/5*(axis.high-axis.low),2),ax+offset,top+k/5*(bottom-top)+4);});g.textAlign='left';
 g.save();g.beginPath();g.rect(left-1,top-1,right-left+2,bottom-top+2);g.clip();for(const s of r.series){if(!s.count)continue;const axis=r.axes.get(s.axis);const y=v=>bottom-(normalized?(s.max===s.min ? .5 :(v-s.min)/(s.max-s.min)):(v-axis.low)/(axis.high-axis.low))*(bottom-top);g.strokeStyle=s.color;g.fillStyle=s.color;g.lineWidth=1.7;g.beginPath();let previous=null;const starts=[];for(const p of s.samples){if(typeof p.v!=='number'||!Number.isFinite(p.v)){previous=null;continue;}const px=x(p.t),py=y(p.v);if(!previous||p.break||p.t-previous.t>3){g.moveTo(px,py);starts.push([px,py]);}else g.lineTo(px,py);previous=p;}g.stroke();for(const [px,py] of starts){g.beginPath();g.arc(px,py,2.5,0,Math.PI*2);g.fill();}}g.restore();
}
$('chart-add').onclick=()=>{if(!log||chartSelections.length>=6)return;const next=chartCatalog.find(f=>!chartSelections.includes(f.id));if(next)chartSelections.push(next.id);renderChartControls();generateChart();};
$('chart-generate').onclick=generateChart;$('chart-scope').onchange=()=>{if(log)generateChart();};$('chart-scale').onchange=()=>{if(log)generateChart();};
$('chart-download').onclick=()=>{if(!chartRendered)return;const out=document.createElement('canvas');out.width=chartCanvas.width;const dpr=window.devicePixelRatio||1;out.height=chartCanvas.height+(chartRendered.series.length*25+20)*dpr;const g=out.getContext('2d');g.fillStyle='#0e1823';g.fillRect(0,0,out.width,out.height);g.drawImage(chartCanvas,0,0);g.setTransform(dpr,0,0,dpr,0,0);g.font='13px Segoe UI, Microsoft YaHei';chartRendered.series.forEach((s,i)=>{g.fillStyle=s.color;g.fillText(`● ${s.label} [${s.unit||'无量纲'}]${s.count?'':' · 此范围无数据'}`,20,chartCanvas.height/dpr+25+i*25);});out.toBlob(blob=>{const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='flight-parameters.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});};
new ResizeObserver(()=>drawParameterChart()).observe(chartCanvas.parentElement);drawParameterChart();
