'use strict';
const {chromium}=require('playwright'),path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||undefined});try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(require('node:url').pathToFileURL(path.join(__dirname,'index.html')).href);
 const data={GPS:[],POS:[],CTUN:[],MODE:[{TimeUS:0,ModeNum:5}],MSG:[{TimeUS:0,Message:'ArduPlane chart fixture'}]};
 for(let i=0;i<=5;i++){data.GPS.push({TimeUS:i*1e6,Status:3,Lat:30+i*.0001,Lng:120+i*.0001,Spd:10+i,Alt:20+i});data.POS.push({TimeUS:i*1e6,RelHomeAlt:i});}for(let i=0;i<=20;i++)data.CTUN.push({TimeUS:i*250000,ThO:40+i});
 await page.locator('#file').setInputFiles({name:'charts.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.waitForFunction(()=>document.querySelector('#status').className==='success');
 assert.deepEqual(await page.evaluate(()=>chartRendered.series.map(s=>s.count)),[6,6]);await page.locator('#chart-add').click();await page.getByLabel('纵轴参数 3',{exact:true}).selectOption('raw:CTUN:ThO');assert.equal(await page.evaluate(()=>chartRendered.series[2].count),21);
 await page.locator('#range-from').fill('1');await page.locator('#range-from').dispatchEvent('change');await page.locator('#range-to').fill('3');await page.locator('#range-to').dispatchEvent('change');assert.deepEqual(await page.evaluate(()=>[chartRendered.start,chartRendered.end,chartRendered.series[2].count]),[1,3,9]);
 const outsidePixels=await page.evaluate(()=>{const c=document.querySelector('#profile'),g=c.getContext('2d'),dpr=devicePixelRatio||1,left=profileX(log.points[rangeStart].elapsed),data=g.getImageData(22*dpr,0,Math.floor((left-30)*dpr),Math.floor((c.clientHeight-25)*dpr)).data;let n=0;for(let i=0;i<data.length;i+=4)if(data[i+1]>70&&data[i+1]>data[i]*1.5&&data[i+2]>45)n++;return n;});assert.ok(outsidePixels>10,'unselected timeline curves must remain visible');
 await page.getByLabel('纵轴参数 1',{exact:true}).selectOption('alt');assert.equal(await page.evaluate(()=>chartRendered.axes.size),2);await page.locator('#chart-scale').selectOption('normalized');assert.equal(await page.evaluate(()=>chartRendered.normalized),true);await page.locator('#chart-scope').selectOption('full');assert.equal(await page.evaluate(()=>chartRendered.series[2].count),21);
 const download=page.waitForEvent('download');await page.locator('#chart-download').click();const file=await download;assert.equal(file.suggestedFilename(),'flight-parameters.png');const bytes=fs.readFileSync(await file.path());assert.equal(bytes.subarray(1,4).toString(),'PNG');assert.ok(bytes.readUInt32BE(16)>=680);
 await page.locator('#chart-scale').selectOption('units');await page.locator('#chart-scope').selectOption('range');await page.locator('.chart-panel').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(__dirname,'chart-preview.png'),fullPage:true});
 for(let i=0;i<3;i++)await page.locator('#chart-add').click();assert.equal(await page.locator('.chart-series-row').count(),6);assert.equal(await page.locator('#chart-add').isDisabled(),true);while(await page.locator('.chart-series-row').count()>1)await page.getByLabel('移除参数 1',{exact:true}).click();await page.getByLabel('纵轴参数 1',{exact:true}).selectOption('voltage');assert.equal(await page.locator('#chart-download').isDisabled(),true);assert.match(await page.locator('#chart-legend').innerText(),/此范围无数据/);
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.ok(await page.locator('.chart-scroll').evaluate(el=>el.scrollWidth>el.clientWidth));assert.deepEqual(errors,[]);console.log('PASS: full timeline context, native-rate chart data, range sync, shared axes, normalization, PNG, six-series limit, missing data and mobile scroll.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
