'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),{normalize}=require('./log-parser.js');
const gps=t=>({TimeUS:t*1e6,Status:3,Lat:1,Lng:1,GCrs:270,Yaw:180});
const normalized=normalize({GPS:[gps(0),gps(1),gps(4)],ATT:[{TimeUS:0,Yaw:450}]});assert.deepEqual(normalized.points.map(p=>p.yaw),[90,90,null]);assert.equal(normalize({GPS:[gps(0)]}).points[0].yaw,null);assert.equal(normalize({GPS:[gps(0)],ATT:[{TimeUS:0,Yaw:-90}]}).points[0].yaw,270);assert.equal(normalize({GPS:[gps(0)],ATT:[{TimeUS:0,Yaw:0}]}).points[0].yaw,0);
(async()=>{const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||undefined});try{
 const page=await browser.newPage({viewport:{width:1440,height:1600}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(require('node:url').pathToFileURL(path.join(__dirname,'index.html')).href);await page.locator('#demo').click();await page.evaluate(()=>{setSelected(400);});
 for(const [yaw,dx,dy] of [[0,0,-31],[90,31,0],[180,0,31],[270,-31,0]]){const pixel=await page.evaluate(({yaw,dx,dy})=>{log.points[selected].yaw=yaw;draw();const p=screen(log.points[selected]),d=window.devicePixelRatio||1;return [...canvas.getContext('2d').getImageData(Math.round((p.x+dx)*d),Math.round((p.y+dy)*d),1,1).data];},{yaw,dx,dy});assert.ok(pixel[0]>220&&pixel[1]>220&&pixel[2]>220,'arrow must point in the recorded cardinal direction');assert.match(await page.locator('#heading-status').innerText(),new RegExp(yaw+'.0°'));}
 await page.evaluate(()=>{log.points[selected].yaw=null;draw();});assert.match(await page.locator('#heading-status').innerText(),/缺失/);await page.evaluate(()=>{log.points[selected].yaw=90;draw();});await page.locator('#heading-visible').uncheck();assert.match(await page.locator('#heading-status').innerText(),/隐藏/);await page.locator('#heading-visible').check();
 await page.evaluate(()=>setSelected(500));assert.match(await page.locator('#heading-status').innerText(),/40.0°/);await page.locator('#play').click();await page.waitForFunction(()=>selected>500);await page.locator('#play').click();const actual=await page.evaluate(()=>log.points[selected].yaw.toFixed(1));assert.ok((await page.locator('#heading-status').innerText()).includes(actual+'°'));
 await page.locator('#track').scrollIntoViewIfNeeded();const hover=await page.evaluate(()=>{const p=screen(log.points[600]),r=canvas.getBoundingClientRect();return{x:p.x+r.x,y:p.y+r.y};});await page.mouse.move(hover.x,hover.y);await page.waitForFunction(()=>hover>=0);assert.ok(await page.evaluate(()=>$('heading-status').textContent.includes(log.points[hover].yaw.toFixed(1)+'°')));
 const download=page.waitForEvent('download');await page.locator('#export').click();assert.equal((await download).suggestedFilename(),'flight-track.png');assert.ok(await page.evaluate(()=>!!canvas.toDataURL()));await page.locator('#language').selectOption('en');assert.match(await page.locator('#heading-status').innerText(),/Nose heading/);await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 console.log('PASS: actual ATT yaw, wrap/zero/staleness/no course fallback, rendered cardinal arrows, toggle, seeking, playback, hover, PNG, language and mobile.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
