'use strict';
let waypointMission=null,waypointsVisible=true,waypointHover=null,waypointSelected=null,waypointLoadToken=0,waypointDisplayed=null,waypointDisplayLanguage=null,waypointFitActive=false;
function waypointPoint(item){const origin=log.points[0],rad=Math.PI/180,dl=((item.lon-origin.lon+540)%360)-180;return {...item,x:6371008.8*dl*rad*Math.cos(origin.lat*rad),y:6371008.8*(item.lat-origin.lat)*rad};}
function waypointAltitude(item){const reference=[0,5].includes(item.frame)?'海拔':[3,6].includes(item.frame)?'相对 Home 高度':[10,11].includes(item.frame)?'地形以上高度':'原始高度';return `${fmt(item.alt)} m · ${t(reference)}`;}
function waypointRows(item){return [[t('任务序号'),String(item.seq)],[t('命令'),`${item.name} (${item.command})`],[t('坐标系'),String(item.frame)],[item.plotted?t('纬度'):'Param 5 / X',fmt(item.lat,7)],[item.plotted?t('经度'):'Param 6 / Y',fmt(item.lon,7)],[item.plotted?t('任务高度'):'Param 7 / Z',item.plotted?waypointAltitude(item):fmt(item.alt,4)],...item.params.map((v,i)=>[`Param ${i+1}`,fmt(v,4)]),[t('文件 Current 标记'),String(item.current)],[t('自动继续'),item.autocontinue?'1':'0'],[t('叠加状态'),t(item.plotted?'可叠加':item.reason)]];}
function waypointDetails(item){if(waypointDisplayed===item&&waypointDisplayLanguage===language)return;waypointDisplayed=item;waypointDisplayLanguage=language;const panel=$('waypoint-details');panel.replaceChildren();if(!item)return;for(const [key,value] of waypointRows(item)){const row=document.createElement('div');row.className='data-row';const label=document.createElement('span'),strong=document.createElement('strong');label.textContent=key;strong.textContent=value;strong.dataset.noTranslate='';row.append(label,strong);panel.append(row);}}
function updateWaypointUI(){const available=!!waypointMission;$('waypoint-visible').disabled=!available;$('waypoint-clear').disabled=!available;$('waypoint-fit').disabled=!log||!waypointMission?.points.length||!waypointsVisible;$('waypoint-inspector').hidden=!available;const select=$('waypoint-item');select.replaceChildren();for(const item of waypointMission?.items||[]){const option=document.createElement('option');option.value=item.seq;option.textContent=`${item.home?'Home':'WP '+item.seq} · ${item.name}`;select.append(option);}if(waypointSelected)select.value=waypointSelected.seq;waypointDetails(waypointSelected);}
function waypointStatus(){if(!waypointMission)return;$('waypoint-status').className='';$('waypoint-status').replaceChildren();const name=document.createElement('span');name.dataset.noTranslate='';name.textContent=waypointMission.filename;$('waypoint-status').append(name,document.createTextNode(` · ${t('任务项')} ${waypointMission.items.length} · ${t('可叠加位置')} ${waypointMission.points.length}${log?'':' · '+t('导入日志后叠加')}`));}
async function importWaypoints(file){const token=++waypointLoadToken;try{if(!/\.waypoints$/i.test(file.name))throw Error('请导入 .waypoints 文件。');const result=WaypointFile.parse(await file.text());if(token!==waypointLoadToken)return;waypointMission={...result,filename:file.name};waypointFitActive=false;waypointHover=null;waypointSelected=result.items[0];waypointsVisible=true;$('waypoint-visible').checked=true;waypointStatus();updateWaypointUI();$('tip').hidden=true;draw();}catch(e){if(token!==waypointLoadToken)return;$('waypoint-status').className='error';$('waypoint-status').textContent=t('航点导入失败：')+t(e.message)+' '+t(waypointMission?'保留上一次成功导入的航点。':'航点未加载。');}finally{if(token===waypointLoadToken)$('waypoint-file').value='';}}
function drawWaypoints(g){if(!log||!waypointMission||!waypointsVisible)return;g.save();g.strokeStyle='#ffe08a';g.lineWidth=1.8;g.setLineDash([7,5]);let previous=null;for(const item of waypointMission.items){if(item.breakRoute)previous=null;if(!item.plotted||item.home)continue;const s=screen(waypointPoint(item));if(previous){g.beginPath();g.moveTo(previous.x,previous.y);g.lineTo(s.x,s.y);g.stroke();}previous=s;}g.setLineDash([]);g.font='bold 11px Segoe UI';for(const item of waypointMission.points){const s=screen(waypointPoint(item));if(s.x<-40||s.y<-40||s.x>W+40||s.y>H+40)continue;g.fillStyle='#0b121c';g.strokeStyle=waypointHover===item||waypointSelected===item?'#fff':'#ffe08a';g.lineWidth=2;g.beginPath();g.moveTo(s.x,s.y-7);g.lineTo(s.x+7,s.y);g.lineTo(s.x,s.y+7);g.lineTo(s.x-7,s.y);g.closePath();g.fill();g.stroke();const label=item.home?'Home':'WP '+item.seq;g.strokeStyle='#0b121c';g.lineWidth=3;g.strokeText(label,s.x+10,s.y-10);g.fillStyle='#ffe08a';g.fillText(label,s.x+10,s.y-10);}g.fillStyle='#ffe08a';g.font='11px Segoe UI';g.fillText('◇ 航点 · 虚线为任务顺序示意',16,20);g.restore();}
function hoverWaypoint(position){waypointHover=null;if(!waypointsVisible||!waypointMission||!log)return false;let distance=10;for(const item of waypointMission.points){const s=screen(waypointPoint(item)),d=Math.hypot(s.x-position.x,s.y-position.y);if(d<distance){distance=d;waypointHover=item;}}if(!waypointHover)return false;hover=-1;details(selected);waypointDetails(waypointHover);const tip=$('tip');tip.replaceChildren(...waypointRows(waypointHover).map(([key,value])=>{const row=document.createElement('div');row.textContent=`${key} · ${value}`;return row;}));tip.hidden=false;tip.style.left=`${Math.max(4,Math.min(position.x+18,W-tip.offsetWidth-8))}px`;tip.style.top=`${Math.max(4,Math.min(position.y+18,H-tip.offsetHeight-8))}px`;draw();return true;}
function fitWaypoints(){if(!log||!waypointMission?.points.length||!waypointsVisible)return;waypointFitActive=true;const points=[...rangePoints(),...waypointMission.points.map(waypointPoint)].map(displayPoint);let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const p of points){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y);}view={cx:(minX+maxX)/2,cy:(minY+maxY)/2,scale:Math.min((W-120)/Math.max(20,maxX-minX),(H-120)/Math.max(20,maxY-minY))};$('tip').hidden=true;draw();}
document.addEventListener('DOMContentLoaded',()=>{
 $('waypoint-file').onchange=e=>{if(e.target.files[0])importWaypoints(e.target.files[0]);};
 $('waypoint-visible').onchange=e=>{waypointsVisible=e.target.checked;if(!waypointsVisible)waypointFitActive=false;waypointHover=null;$('tip').hidden=true;updateWaypointUI();draw();};
 $('waypoint-clear').onclick=()=>{++waypointLoadToken;waypointMission=null;waypointFitActive=false;waypointHover=null;waypointSelected=null;$('tip').hidden=true;$('waypoint-status').className='';$('waypoint-status').textContent='支持 QGC WPL 110；航点仅在本机读取。';updateWaypointUI();draw();};
 $('waypoint-fit').onclick=fitWaypoints;$('waypoint-item').onchange=e=>{waypointSelected=waypointMission.items.find(item=>item.seq===Number(e.target.value));waypointHover=null;waypointDetails(waypointSelected);$('tip').hidden=true;draw();};
 $('language').addEventListener('change',()=>{waypointDetails(waypointSelected);if($('waypoint-status').className!=='error')waypointStatus();});updateWaypointUI();
});
